// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sqrt.proto

package sqrtpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SqrtRequestWithDeadline struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqrtRequestWithDeadline) Reset()         { *m = SqrtRequestWithDeadline{} }
func (m *SqrtRequestWithDeadline) String() string { return proto.CompactTextString(m) }
func (*SqrtRequestWithDeadline) ProtoMessage()    {}
func (*SqrtRequestWithDeadline) Descriptor() ([]byte, []int) {
	return fileDescriptor_746f45ae1873c6cc, []int{0}
}

func (m *SqrtRequestWithDeadline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqrtRequestWithDeadline.Unmarshal(m, b)
}
func (m *SqrtRequestWithDeadline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqrtRequestWithDeadline.Marshal(b, m, deterministic)
}
func (m *SqrtRequestWithDeadline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqrtRequestWithDeadline.Merge(m, src)
}
func (m *SqrtRequestWithDeadline) XXX_Size() int {
	return xxx_messageInfo_SqrtRequestWithDeadline.Size(m)
}
func (m *SqrtRequestWithDeadline) XXX_DiscardUnknown() {
	xxx_messageInfo_SqrtRequestWithDeadline.DiscardUnknown(m)
}

var xxx_messageInfo_SqrtRequestWithDeadline proto.InternalMessageInfo

func (m *SqrtRequestWithDeadline) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SqrtResponseWithDeadline struct {
	Root                 int32    `protobuf:"varint,1,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqrtResponseWithDeadline) Reset()         { *m = SqrtResponseWithDeadline{} }
func (m *SqrtResponseWithDeadline) String() string { return proto.CompactTextString(m) }
func (*SqrtResponseWithDeadline) ProtoMessage()    {}
func (*SqrtResponseWithDeadline) Descriptor() ([]byte, []int) {
	return fileDescriptor_746f45ae1873c6cc, []int{1}
}

func (m *SqrtResponseWithDeadline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqrtResponseWithDeadline.Unmarshal(m, b)
}
func (m *SqrtResponseWithDeadline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqrtResponseWithDeadline.Marshal(b, m, deterministic)
}
func (m *SqrtResponseWithDeadline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqrtResponseWithDeadline.Merge(m, src)
}
func (m *SqrtResponseWithDeadline) XXX_Size() int {
	return xxx_messageInfo_SqrtResponseWithDeadline.Size(m)
}
func (m *SqrtResponseWithDeadline) XXX_DiscardUnknown() {
	xxx_messageInfo_SqrtResponseWithDeadline.DiscardUnknown(m)
}

var xxx_messageInfo_SqrtResponseWithDeadline proto.InternalMessageInfo

func (m *SqrtResponseWithDeadline) GetRoot() int32 {
	if m != nil {
		return m.Root
	}
	return 0
}

func init() {
	proto.RegisterType((*SqrtRequestWithDeadline)(nil), "sqrt.SqrtRequestWithDeadline")
	proto.RegisterType((*SqrtResponseWithDeadline)(nil), "sqrt.SqrtResponseWithDeadline")
}

func init() {
	proto.RegisterFile("sqrt.proto", fileDescriptor_746f45ae1873c6cc)
}

var fileDescriptor_746f45ae1873c6cc = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2e, 0x2c, 0x2a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x0c, 0xb9, 0xc4, 0x83, 0x0b,
	0x8b, 0x4a, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xc2, 0x33, 0x4b, 0x32, 0x5c, 0x52, 0x13,
	0x53, 0x72, 0x32, 0xf3, 0x52, 0x85, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x25, 0x3d, 0x2e, 0x09, 0x88, 0x96, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x14, 0x3d, 0x42, 0x5c, 0x2c, 0x45, 0xf9, 0xf9, 0x25, 0x50, 0x1d, 0x60,
	0xb6, 0x51, 0x02, 0x17, 0x67, 0x72, 0x62, 0x4e, 0x72, 0x3c, 0xc8, 0x3e, 0xa1, 0x60, 0x2e, 0x01,
	0xe7, 0xc4, 0x9c, 0x64, 0x14, 0x4d, 0xb2, 0x7a, 0x60, 0x67, 0xe1, 0x70, 0x87, 0x94, 0x1c, 0xb2,
	0x34, 0xa6, 0x9d, 0x4a, 0x0c, 0x4e, 0x1c, 0x51, 0x6c, 0x20, 0x25, 0x05, 0x49, 0x49, 0x6c, 0x60,
	0xbf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0xfe, 0x8f, 0xfb, 0xe9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalcSqrtClient is the client API for CalcSqrt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalcSqrtClient interface {
	CalcWithDeadline(ctx context.Context, in *SqrtRequestWithDeadline, opts ...grpc.CallOption) (*SqrtResponseWithDeadline, error)
}

type calcSqrtClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcSqrtClient(cc grpc.ClientConnInterface) CalcSqrtClient {
	return &calcSqrtClient{cc}
}

func (c *calcSqrtClient) CalcWithDeadline(ctx context.Context, in *SqrtRequestWithDeadline, opts ...grpc.CallOption) (*SqrtResponseWithDeadline, error) {
	out := new(SqrtResponseWithDeadline)
	err := c.cc.Invoke(ctx, "/sqrt.calc_sqrt/CalcWithDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcSqrtServer is the server API for CalcSqrt service.
type CalcSqrtServer interface {
	CalcWithDeadline(context.Context, *SqrtRequestWithDeadline) (*SqrtResponseWithDeadline, error)
}

// UnimplementedCalcSqrtServer can be embedded to have forward compatible implementations.
type UnimplementedCalcSqrtServer struct {
}

func (*UnimplementedCalcSqrtServer) CalcWithDeadline(ctx context.Context, req *SqrtRequestWithDeadline) (*SqrtResponseWithDeadline, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcWithDeadline not implemented")
}

func RegisterCalcSqrtServer(s *grpc.Server, srv CalcSqrtServer) {
	s.RegisterService(&_CalcSqrt_serviceDesc, srv)
}

func _CalcSqrt_CalcWithDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqrtRequestWithDeadline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcSqrtServer).CalcWithDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sqrt.calc_sqrt/CalcWithDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcSqrtServer).CalcWithDeadline(ctx, req.(*SqrtRequestWithDeadline))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalcSqrt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sqrt.calc_sqrt",
	HandlerType: (*CalcSqrtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalcWithDeadline",
			Handler:    _CalcSqrt_CalcWithDeadline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sqrt.proto",
}
