// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Room struct {
	Length               int32    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Room) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Room) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type CalcRequest struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcRequest) Reset()         { *m = CalcRequest{} }
func (m *CalcRequest) String() string { return proto.CompactTextString(m) }
func (*CalcRequest) ProtoMessage()    {}
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{1}
}

func (m *CalcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcRequest.Unmarshal(m, b)
}
func (m *CalcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcRequest.Marshal(b, m, deterministic)
}
func (m *CalcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcRequest.Merge(m, src)
}
func (m *CalcRequest) XXX_Size() int {
	return xxx_messageInfo_CalcRequest.Size(m)
}
func (m *CalcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcRequest proto.InternalMessageInfo

func (m *CalcRequest) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type CalcResponse struct {
	Axial                []float32 `protobuf:"fixed32,1,rep,packed,name=axial,proto3" json:"axial,omitempty"`
	Tangential           []float32 `protobuf:"fixed32,2,rep,packed,name=tangential,proto3" json:"tangential,omitempty"`
	Oblique              []float32 `protobuf:"fixed32,3,rep,packed,name=oblique,proto3" json:"oblique,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CalcResponse) Reset()         { *m = CalcResponse{} }
func (m *CalcResponse) String() string { return proto.CompactTextString(m) }
func (*CalcResponse) ProtoMessage()    {}
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{2}
}

func (m *CalcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcResponse.Unmarshal(m, b)
}
func (m *CalcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcResponse.Marshal(b, m, deterministic)
}
func (m *CalcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcResponse.Merge(m, src)
}
func (m *CalcResponse) XXX_Size() int {
	return xxx_messageInfo_CalcResponse.Size(m)
}
func (m *CalcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcResponse proto.InternalMessageInfo

func (m *CalcResponse) GetAxial() []float32 {
	if m != nil {
		return m.Axial
	}
	return nil
}

func (m *CalcResponse) GetTangential() []float32 {
	if m != nil {
		return m.Tangential
	}
	return nil
}

func (m *CalcResponse) GetOblique() []float32 {
	if m != nil {
		return m.Oblique
	}
	return nil
}

func init() {
	proto.RegisterType((*Room)(nil), "calc.Room")
	proto.RegisterType((*CalcRequest)(nil), "calc.CalcRequest")
	proto.RegisterType((*CalcResponse)(nil), "calc.CalcResponse")
}

func init() {
	proto.RegisterFile("calc.proto", fileDescriptor_a2b9900dc883ea68)
}

var fileDescriptor_a2b9900dc883ea68 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xc9, 0x9f, 0x06, 0x74, 0x65, 0xe1, 0x84, 0x90, 0xc5, 0x50, 0x55, 0x99, 0xba, 0x50,
	0xa4, 0xb2, 0x33, 0xc0, 0xca, 0x64, 0x36, 0x06, 0x24, 0x27, 0x9c, 0x12, 0x4b, 0xae, 0x2f, 0x4d,
	0x1c, 0xe0, 0xe3, 0x23, 0xfb, 0xa8, 0x94, 0xcd, 0xbf, 0xf7, 0x9e, 0xfc, 0x9e, 0x0e, 0xa0, 0x35,
	0xae, 0xdd, 0x0f, 0x23, 0x07, 0xc6, 0x32, 0xbe, 0xeb, 0x37, 0x28, 0x35, 0xf3, 0x11, 0xef, 0xa0,
	0x72, 0xe4, 0xbb, 0xd0, 0xab, 0x6c, 0x9b, 0xed, 0x56, 0xfa, 0x9f, 0xf0, 0x16, 0x56, 0x3f, 0xf6,
	0x2b, 0xf4, 0x2a, 0x4f, 0xb2, 0x40, 0x4c, 0xf7, 0x64, 0xbb, 0x3e, 0xa8, 0x42, 0xd2, 0x42, 0xf5,
	0x03, 0xac, 0x5f, 0x8d, 0x6b, 0x35, 0x9d, 0x66, 0x9a, 0x02, 0x6e, 0xa0, 0x1c, 0x99, 0x8f, 0xe9,
	0xcb, 0xf5, 0x01, 0xf6, 0xa9, 0x3d, 0xd6, 0xe9, 0xa4, 0xd7, 0x9f, 0x70, 0x2d, 0xf1, 0x69, 0x60,
	0x3f, 0x51, 0x2c, 0x33, 0xbf, 0xd6, 0x38, 0x95, 0x6d, 0x8b, 0x5d, 0xae, 0x05, 0x70, 0x03, 0x10,
	0x8c, 0xef, 0xc8, 0x87, 0x68, 0xe5, 0xc9, 0x5a, 0x28, 0xa8, 0xe0, 0x92, 0x1b, 0x67, 0x4f, 0x33,
	0xa9, 0x22, 0x99, 0x67, 0x3c, 0x3c, 0xcb, 0x9c, 0x77, 0x1a, 0xbf, 0x6d, 0x4b, 0xf8, 0x08, 0x65,
	0x44, 0xbc, 0x91, 0x21, 0x8b, 0xa5, 0xf7, 0xb8, 0x94, 0x64, 0x4d, 0x7d, 0xf1, 0x72, 0xf5, 0x51,
	0x45, 0x79, 0x68, 0x9a, 0x2a, 0xdd, 0xec, 0xe9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x91, 0x0d, 0x9d,
	0xee, 0x41, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalcServiceClient is the client API for CalcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalcServiceClient interface {
	Calc(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error)
}

type calcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcServiceClient(cc grpc.ClientConnInterface) CalcServiceClient {
	return &calcServiceClient{cc}
}

func (c *calcServiceClient) Calc(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error) {
	out := new(CalcResponse)
	err := c.cc.Invoke(ctx, "/calc.CalcService/Calc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcServiceServer is the server API for CalcService service.
type CalcServiceServer interface {
	Calc(context.Context, *CalcRequest) (*CalcResponse, error)
}

// UnimplementedCalcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalcServiceServer struct {
}

func (*UnimplementedCalcServiceServer) Calc(ctx context.Context, req *CalcRequest) (*CalcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calc not implemented")
}

func RegisterCalcServiceServer(s *grpc.Server, srv CalcServiceServer) {
	s.RegisterService(&_CalcService_serviceDesc, srv)
}

func _CalcService_Calc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServiceServer).Calc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.CalcService/Calc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServiceServer).Calc(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalcService",
	HandlerType: (*CalcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calc",
			Handler:    _CalcService_Calc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc.proto",
}
